<?php

function testbed_issues_init() {
    
}

// Implementation of hook_menu function.
function testbed_issues_menu() {
    $items['nctoolbox-issues'] = array(
        'title' => 'NC Toolbox Issues',
        'page callback' => 'nctoolbox_issues_page_default',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('administer testbed_issues'),
    );
    
    $items['ncsos-issues'] = array(
        'title' => 'ncSOS Issues',
        'page callback' => 'ncsos_issues_page_default',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('administer testbed_issues'),
    );
    
    $items['imeds-issues'] = array(
        'title' => 'imeds2netcdf crawler Issues',
        'page callback' => 'imeds_issues_page_default',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('administer testbed_issues'),
    );

    $items['issues_response'] = array(
        'title' => 'issues_response',
        'page callback' => 'testbed_issues_response',
        'access arguments' => array('administer testbed_issues'),
        'type' => MENU_CALLBACK,
    );

    return $items;
}

function nctoolbox_issues_page_default() {
    return drupal_get_form('nctoolbox_issues_form');
}

function ncsos_issues_page_default() {
    return drupal_get_form('ncsos_issues_form');
}

function imeds_issues_page_default() {
    return drupal_get_form('imeds_issues_form');
}

function testbed_issues_response() {
    $url="";
    if (isset($_GET['url'])) {
        $url = $_GET['url'];
        //echo "<script language=javascript>alert('anil')</script>";
    } else if (isset($_POST['url'])) {
        $url = $_POST['url'];
    }


    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    // Set so curl_exec returns the result instead of outputting it.
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    // Get the response and close the channel.
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    //curl_setopt($ch, CURLOPT_HEADER,true);
    $response = curl_exec($ch);   
    header('Content-Type: text/xml');
    curl_close($ch);
    echo $response;
}

// Implementation of hook_ form function ( to bring out the layout of the drupal form)
function nctoolbox_issues_form() {
    $modulepath = 'sites/all/modules/testbed_catalog';
    drupal_add_css($modulepath . '/includes/ext/resources/css/ext-all.css');
    drupal_add_css($modulepath . '/includes/css/OpenLayers/openlayer_style.css');
    drupal_add_css($modulepath . '/includes/css/custom_search.css');

    drupal_add_js($modulepath . '/includes/ext/adapter/ext/ext-base-debug.js', 'module', 'header', FALSE, TRUE, TRUE);
    drupal_add_js($modulepath . '/includes/ext/ext-all-debug.js', 'module', 'header', FALSE, TRUE, TRUE);    

    drupal_add_js($modulepath . '/modules/testbed_issues/js/get-testbed-issues.js', 'module', 'header', FALSE, TRUE, FALSE);

    $form['modelsGrid'] = array(
        '#type' => 'markup',
        '#prefix' => '<div id="grid_issues"></div>',
        '#value' => ' ',
    );

    return $form;
}

function ncsos_issues_form() {
    $modulepath = 'sites/all/modules/testbed_catalog';
    drupal_add_css($modulepath . '/includes/ext/resources/css/ext-all.css');
    drupal_add_css($modulepath . '/includes/css/OpenLayers/openlayer_style.css');
    drupal_add_css($modulepath . '/includes/css/custom_search.css');

    drupal_add_js($modulepath . '/includes/ext/adapter/ext/ext-base-debug.js', 'module', 'header', FALSE, TRUE, TRUE);
    drupal_add_js($modulepath . '/includes/ext/ext-all-debug.js', 'module', 'header', FALSE, TRUE, TRUE);   
    drupal_add_js($modulepath . '/modules/testbed_issues/js/get-ncsos-issues.js', 'module', 'header', FALSE, TRUE, FALSE);
    drupal_add_js($modulepath . '/modules/testbed_issues/js/FeedGrid.js', 'module', 'header', FALSE, TRUE, FALSE);
     
    $form['modelsGrid'] = array(
        '#type' => 'markup',
        '#prefix' => '<div id="grid_issues"></div>',
        '#value' => ' ',
    );

    return $form;
}

function imeds_issues_form() {
    $modulepath = 'sites/all/modules/testbed_catalog';
    drupal_add_css($modulepath . '/includes/ext/resources/css/ext-all.css');
    drupal_add_css($modulepath . '/includes/css/OpenLayers/openlayer_style.css');
    drupal_add_css($modulepath . '/includes/css/custom_search.css');

    drupal_add_js($modulepath . '/includes/ext/adapter/ext/ext-base-debug.js', 'module', 'header', FALSE, TRUE, TRUE);
    drupal_add_js($modulepath . '/includes/ext/ext-all-debug.js', 'module', 'header', FALSE, TRUE, TRUE);  
    drupal_add_js($modulepath . '/modules/testbed_issues/js/get-imeds-issues.js', 'module', 'header', FALSE, TRUE, FALSE);
    drupal_add_js($modulepath . '/modules/testbed_issues/js/FeedGrid.js', 'module', 'header', FALSE, TRUE, FALSE);

    $form['modelsGrid'] = array(
        '#type' => 'markup',
        '#prefix' => '<div id="grid_issues"></div>',
        '#value' => ' ',
    );

    return $form;
}

function testbed_issues_form_alter(&$form, &$form_state, $form_id) {
    if ($form_id == "views_exposed_form") {
        global $base_url;       
        $modulepath = 'sites/all/modules/testbed_catalog';   
        drupal_add_css($modulepath . '/includes/ext/resources/css/ext-all.css');     
        drupal_add_css($modulepath . '/includes/css/custom_search.css');       
        drupal_add_js($modulepath . '/includes/ext/adapter/ext/ext-base-debug.js', 'module', 'header', FALSE, TRUE, TRUE);
        drupal_add_js($modulepath . '/includes/ext/ext-all-debug.js', 'module', 'header', FALSE, TRUE, TRUE);      
        drupal_add_js($modulepath . '/includes/js/GridRowExpander.js', 'module', 'header', FALSE, TRUE, FALSE);       
        drupal_add_js($modulepath . '/modules/testbed_issues/js/get-testbed-issues.js', 'module', 'header', FALSE, TRUE, FALSE);
        drupal_add_js($modulepath . '/modules/testbed_issues/js/FeedGrid.js', 'module', 'header', FALSE, TRUE, FALSE);
        return $form;
    }
}

function testbed_issues_perm() {
    return array('administer testbed_issues');
}

?>