<?php
function catalog_search_init() { 
     
}


function catalog_search_css_alter(&$css) {
     unset($css["themes/pressblog/style.css"]);
}


// Implementation of hook_menu function.
function catalog_search_menu() {
    $items['catalog-search'] = array(
        'title' => 'catalog-search',
        'page callback' => 'catalog_search_page_default',
        'type' => MENU_NORMAL_ITEM,
        'access arguments' => array('administer catalog_search'),
    );
    
    $items['catalogsearchresponse'] = array(
        'title' =>'catalogresponse',
        'page callback' => 'catalog_search_response',
        'access arguments' => array('administer catalog_search'),
        'type' => MENU_CALLBACK,
  );

    return $items;
}

function catalog_search_page_default() {
     return drupal_get_form('catalog_search_form');
   }

function catalog_search_response() {
    
    
    if (isset($_POST['isourl'])) {
        $url = $_POST['isourl'];
        $data=$_POST['isodata'];
    } elseif (isset($_GET['isourl'])) {
        $url = $_GET['isourl'];
        $data=$_GET['isodata'];
    } else {
        $url = '';
        $data='';
    } 
        
    $optional_headers="Content-type: text/xml";   
    $params = array('http' => array(
            'method' => 'POST',
            'content' => $data
            ));
    if ($optional_headers !== null) {
        $params['http']['header'] = $optional_headers;
    }
    
    $ctx = stream_context_create($params);
     
    $fp = @fopen($url, 'rb', false, $ctx);  
    
    if (!$fp) {
        throw new Exception("Problem with $url, $php_errormsg");
    }       
    $response = @stream_get_contents($fp);    
    if ($response === false) {
        throw new Exception("Problem reading data from $url, $php_errormsg");
    }
    echo $response;
    

}

// Implementation of hook_ form function ( to bring out the layout of the drupal form)
function catalog_search_form() {
     
    // $modulepath=drupal_get_path('module', 'catalog_search');
     $modulepath ='sites/all/modules/testbed_catalog';
     
     drupal_add_css($modulepath. '/includes/ext/resources/css/ext-all.css'); 
     drupal_add_css($modulepath. '/includes/css/OpenLayers/openlayer_style.css');
     drupal_add_css($modulepath. '/includes/css/custom_search.css'); 
     
     drupal_add_js($modulepath . '/includes/ext/adapter/ext/ext-base-debug.js', 'module', 'header', FALSE, TRUE, TRUE);
     drupal_add_js($modulepath . '/includes/ext/ext-all-debug.js', 'module', 'header', FALSE, TRUE, TRUE);     
    
     drupal_add_js($modulepath. '/includes/geoext/lib/GeoExt.js','module','header',FALSE,TRUE,FALSE); 
     drupal_add_js($modulepath. '/includes/geoext/lib/OpenLayers.js','module','header',FALSE,TRUE,FALSE);    

     drupal_add_js($modulepath. '/includes/js/GridRowExpander.js','module','header',FALSE,TRUE,FALSE);       
   
     drupal_add_js($modulepath. '/modules/catalog_search/js/get-catalog-search.js','module','header',FALSE,TRUE,FALSE);
    

      $form['searchpanel'] = array(
            '#type' => 'markup',
            '#prefix' => ' <div id="searchpanel">                 
                         </div>',
            '#value'=>' ',
    );      

    return $form;
}

function catalog_search_perm() {
  return array('administer catalog_search');
}
?>